name: Tests

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        working-directory: .\checkyourlife2.0\
        with:
          node-version: "12.x"
      - name: Jest run
        run: npm test
