name: Tests

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        working-directory: checkyourlife2.0
        run: npm install
      - name: Run Jest
        working-directory: checkyourlife2.0
        run: npm run test
