name: Tests

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: go to checkyourlife
        run: cd checkyourlife2.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jest run
        run: npm test
