name: Tests

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
        working-directory: ./checkyourlife2.0
      - name: Jest run
        run: npm test
